% test script for 'genOFDMsignal' function
close all;
clearvars;
clc;

% EXAMPLE 1
% will generate OFDM signal with default params and save the signal in
% 'signal.txt' in the current directory
genOFDMsignal(); 

% EXAMPLE 2
dataLen = 20; % length of data to generate
N = 32;         % # subcarriers
M = 4;          % M-QAM for each subcarrier
getQAMsyms(M);  % show the constellation
tSigAco = genOFDMsignal(... % Variable Arguments to the function
    'data',dataLen,...          
    'OFDMtype','ACOOFDM',...    
    'N',N,...
    'Symbols',getQAMsyms(M),...
    'Scale',1,...
    'Offset',0,...
    'ClipLow',0,...
    'ClipHigh',5,...
    'Seed',0,...
    'FileType','text',...
    'FileName','TestAcoOfdm.txt');                               
figure;
stem(1:numel(tSigAco),tSigAco);
title('Example ACO-OFDM signal');
xlabel('time');
ylabel('signal intensity');

% EXAMPLE 3
N = 64; % # subcarriers
M = 16; % M-QAM for each subcarrier
getQAMsyms(M); % show the constellation
data = randi(M,[20 1]); % Generate data to feed to the function
[tSigDco,tSigM,fSigM] = genOFDMsignal(... % Variable Arguments to the function
    'data',data,...          
    'OFDMtype','DCOOFDM',...    
    'N',N,...
    'Symbols',getQAMsyms(M),...
    'Scale',1,...
    'Offset',0.1,...
    'ClipLow',0,...
    'FileType','text',...
    'FileName','TestDcoOfdm.txt');                               
figure;
stem(1:numel(tSigDco),tSigDco);
title('Example DCO-OFDM signal');
xlabel('time');
ylabel('signal intensity');
